# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75f8e26fefbf4acb4820c36c90331b6a5cff8e5f2ddb60e9abefffa0c37fafb903200684285e1f2b3b26aeb80c5887b9cca1d55a176f8b9e7df57e178773535d

test:
  secret_key_base: 7055948a6f2f15f9a3583872148bce5534ee875bcb3c43381086c3601328c4acbdfd8a5c631a21338d823c124777a02cc6f8daeaf5dce226e41a3d2efdc509ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
